# migration.yml

name: Bitbucket Server to GitHub Migration

on:
  workflow_dispatch: # Allows manual trigger of the migration workflow

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "GH_DEBUG=true" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y
          
      - name: Install GEI Extension
        env: 
          GH_TOKEN: ${{ secrets.TOKEN }} 
        run: |
          gh extension install github/gh-gei

      - name: Install the BBS2GH extension of the GitHub CLI
        env: 
          GH_TOKEN: ${{ secrets.TOKEN }} 
        run: |
          gh extension install github/gh-bbs2gh
          gh extension upgrade github/gh-bbs2gh
          
      - name: Authentication status
        run: |
          gh auth status

      - name: Set environment variables
        run: |
          echo "BITBUCKET_SERVER_URL=${{ secrets.BITBUCKET_SERVER_URL }}" >> $GITHUB_ENV
          echo "BITBUCKET_SERVER_TOKEN=${{ secrets.BITBUCKET_SERVER_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_ORG=${{ secrets.ORG }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "BITBUCKET_SERVER_PROJECT_KEY=${{ secrets.BITBUCKET_SERVER_PROJECT_KEY }}" >> $GITHUB_ENV
          echo "GH_PAT=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "BBS_USERNAME=${{ secrets.BBS_USERNAME }}" >> $GITHUB_ENV
          echo "BBS_PASSWORD=${{ secrets.BBS_PASSWORD }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Install jq (JSON processor)
        run: sudo apt-get install jq
          
      - name: Make migration script executable
        run: chmod +x bbs-migration.sh

      - name: Run Bitbucket Server to GitHub migration script with logging
        run: |
          ./bbs-migration.sh "${{ secrets.BITBUCKET_SERVER_PROJECT_KEY }}" "hello-world-app" 2>&1 | tee migration.log
        continue-on-error: true
        
      - name: Upload Logs
        if: failure() || always()
        uses: actions/upload-artifact@v3
        with:
          name: migration-logs
          path: migration.log
